/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elementaryschoolmanagementsystem;

import com.aspose.email.MailAddress;
import com.aspose.email.MailMessage;
import com.aspose.email.SmtpClient;
import java.nio.charset.Charset;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AddTeacher extends javax.swing.JFrame implements DBUpdateInterface{

    private int id;
    private String firstname;
    private String lastname;
    private String homeroomClass;
    private String subject;
    private String subjectC1;
    private String subjectC2;
    private String subjectC3;
    private String subjectC4;
    private String subjectC5;
    private String contactno;
    private String email;
    private String address;
    private final String category="teacher";
    private final String password="welcome@123";
    LinkedList<String> listClass=new LinkedList<String>();// implementation of linked list to store subject classes
    
    
    public AddTeacher() {
        initComponents();
        this.setLocationRelativeTo(null);
        Random r = new Random();
        id  = r.nextInt(200);
        this.tchrID_txt.setText(Integer.toString(id));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        save_btn = new javax.swing.JButton();
        tchrID_txt = new javax.swing.JTextField();
        teacherFirstName_txt = new javax.swing.JTextField();
        teacherLastName_txt = new javax.swing.JTextField();
        teacherPhoneNumber_txt = new javax.swing.JTextField();
        teacherEmailID_txt = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        teacherSubject_combo = new javax.swing.JComboBox();
        class_combo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        c1a = new javax.swing.JCheckBox();
        c1b = new javax.swing.JCheckBox();
        c1c = new javax.swing.JCheckBox();
        c1d = new javax.swing.JCheckBox();
        c2a = new javax.swing.JCheckBox();
        c2b = new javax.swing.JCheckBox();
        c2c = new javax.swing.JCheckBox();
        c2d = new javax.swing.JCheckBox();
        c3a = new javax.swing.JCheckBox();
        c3b = new javax.swing.JCheckBox();
        c3c = new javax.swing.JCheckBox();
        c3d = new javax.swing.JCheckBox();
        c4a = new javax.swing.JCheckBox();
        c4b = new javax.swing.JCheckBox();
        c4c = new javax.swing.JCheckBox();
        c4d = new javax.swing.JCheckBox();
        c5a = new javax.swing.JCheckBox();
        c5b = new javax.swing.JCheckBox();
        c5c = new javax.swing.JCheckBox();
        c5d = new javax.swing.JCheckBox();

        jButton2.setText("jButton1");

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jTextField6.setText("jTextField1");

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jTextField8.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Teacher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 709));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Elementary School Manager");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(518, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 999, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel2.setText("Teacher ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 161, 113, 39));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 207, 113, 39));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel4.setText("HomeRoom Class");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 305, 154, 39));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel5.setText("Subject");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 367, 113, 39));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel6.setText("Phone number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 436, 126, 39));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel8.setText("Email ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 493, 113, 39));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel9.setText("Last Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 253, 113, 39));

        save_btn.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        save_btn.setText("Save and Email Login Credentials");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel1.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 571, 250, 40));

        tchrID_txt.setEditable(false);
        tchrID_txt.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(tchrID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 165, 220, -1));

        teacherFirstName_txt.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(teacherFirstName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 211, 220, -1));

        teacherLastName_txt.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(teacherLastName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 257, 220, -1));

        teacherPhoneNumber_txt.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(teacherPhoneNumber_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 440, 220, -1));

        teacherEmailID_txt.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(teacherEmailID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 493, 220, -1));

        back_btn.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 571, -1, 40));

        teacherSubject_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Mathematics", "Hindi", "Science", "English", "Social Studies", "General Knowledge", "ICT", " " }));
        jPanel1.add(teacherSubject_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 384, 220, -1));

        class_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1A", "1B", "1C", "1D", "2A", "2B", "2C", "2D", "3A", "3B", "3C", "3D", "4A", "4B", "4C", "4D", "5A", "5B", "5C", "5D" }));
        class_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_comboActionPerformed(evt);
            }
        });
        jPanel1.add(class_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 315, 220, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Subject Classes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(51, 0, 153))); // NOI18N

        c1a.setText("1 A");

        c1b.setText("1 B");

        c1c.setText("1 C");

        c1d.setText("1 D");

        c2a.setText("2 A");

        c2b.setText("2 B");

        c2c.setText("2 C");

        c2d.setText("2 D");

        c3a.setText("3 A");

        c3b.setText("3 B");

        c3c.setText("3 C");

        c3d.setText("3 D");

        c4a.setText("4 A");

        c4b.setText("4 B");

        c4c.setText("4 C");

        c4d.setText("4 D");

        c5a.setText("5 A");

        c5b.setText("5 B");

        c5c.setText("5 C");

        c5d.setText("5 D");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(c5a)
                        .addGap(32, 32, 32)
                        .addComponent(c5b)
                        .addGap(38, 38, 38)
                        .addComponent(c5c))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c4a)
                            .addComponent(c3a)
                            .addComponent(c2a)
                            .addComponent(c1a))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(c4b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(c4c))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(c3b)
                                    .addGap(38, 38, 38)
                                    .addComponent(c3c))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(c1b)
                                    .addGap(38, 38, 38)
                                    .addComponent(c1c))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(c2b)
                                    .addGap(38, 38, 38)
                                    .addComponent(c2c))))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(c1d))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c2d, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c3d, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c4d, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c5d, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1a)
                    .addComponent(c1b)
                    .addComponent(c1c)
                    .addComponent(c1d))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2a)
                    .addComponent(c2b)
                    .addComponent(c2c)
                    .addComponent(c2d))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c3a)
                    .addComponent(c3b)
                    .addComponent(c3c)
                    .addComponent(c3d))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c4a)
                    .addComponent(c4b)
                    .addComponent(c4c)
                    .addComponent(c4d))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c5a)
                    .addComponent(c5b)
                    .addComponent(c5c)
                    .addComponent(c5d))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 161, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        CoordinatorDashboard db=new CoordinatorDashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed
public boolean checkClassValidation(){ // to make sure no teacher is assinged more than 6 classes total
                                       // 1 homeroom class that cannot be subject class
                                       // Exactly 5 subject classes have to be selected from the check boxes
    int count=0;// inital count of classes added
    boolean flag;// test condition
        if(c1a.isSelected()){// if combo box for class 1 is selected
            // below if statement checks if homeroom class is not equal to the subject class selected         
            if(!(c1a.getText().equalsIgnoreCase(this.class_combo.getSelectedItem().toString())))// fetching value from checkbox
                
            {
                this.listClass.add("1A");// if subject class is not equal to homeroom class, add subject class to linked list
                count++;
            
            }
            else{
               c1a.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class "+this.class_combo.getSelectedItem().toString());  ;
            }
            
            
        }
       if(c1b.isSelected()){
            
            if(!(c1b.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("1B");
                count++;
            
            }
            else{
                c1b.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c1c.isSelected()){
            
            if(!(c1c.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("1C");
                count++;
            
            }
            else{
                c1c.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       if(c1d.isSelected()){
            
            if(!(c1d.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("1D");
                count++;
            
            }
            else{
                c1d.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c2a.isSelected()){
            
            if(!(c2a.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("2A");
                count++;
            
            }
            else{
                c2a.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       if(c2b.isSelected()){
            
            if(!(c2b.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("2B");
                count++;
            
            }
            else{
                c2b.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c2c.isSelected()){
            
            if(!(c2c.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("2C");
                count++;
            
            }
            else{
                c2c.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c2d.isSelected()){
            
            if(!(c2d.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("2D");
                count++;
            
            }
            else{
                c2d.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c3a.isSelected()){
            
            if(!(c3a.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("3A");
                count++;
            
            }
            else{
                c3a.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c3b.isSelected()){
            
            if(!(c3b.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("3B");
                count++;
            
            }
            else{
                c3b.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c3c.isSelected()){
            
            if(!(c3c.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("3C");
                count++;
            
            }
            else{
                c3c.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c3d.isSelected()){
            
            if(!(c3d.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("3D");
                count++;
            
            }
            else{
                c3d.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c4a.isSelected()){
            
            if(!(c4a.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("4A");
                count++;
            
            }
            else{
                c4a.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c4b.isSelected()){
            
            if(!(c4b.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("4B");
                count++;
            
            }
            else{
                c4b.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c4c.isSelected()){
            
            if(!(c4c.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("4C");
                count++;
            
            }
            else{
                c4c.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c4d.isSelected()){
            
            if(!(c4d.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("4D");
                count++;
            
            }
            else{
                c4d.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c5a.isSelected()){
            
            if(!(c5a.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("5A");
                count++;
            
            }
            else{
                c5a.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c5b.isSelected()){
            
            if(!(c5b.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("5B");
                count++;
            
            }
            else{
                c5b.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c5c.isSelected()){
            
            if(!(c5c.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("5C");
                count++;
            
            }
            else{
                c5c.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
       
       if(c5d.isSelected()){
            
            if(!(c5d.getText().equals(this.class_combo.getSelectedItem().toString())))
            {
                this.listClass.add("5D");
                count++;
            
            }
            else{
                c5d.setSelected(false);
              JOptionPane.showMessageDialog(this,"Subject Class cannot be Home Room class");  
            }
            
            
        }
      //As a subject teacher only 5 classes can be alloted to specific teacher
        if(count!=5){// check if only 5 subject classes can be selected
            JOptionPane.showMessageDialog(this,"Only 5 classes can be selected");
            flag=false;
        }
        else{
            flag=true;
            
        }
    
        
        //home room validation: only one teacher can be alloted for any specific home room class
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=Db_Connection.connectDbMethod();
            Statement s=con.createStatement();
            ResultSet r=s.executeQuery("select * from teacher_details");// selecting the entire data from table teacher_details
            while(r.next()){// loop untill all columns are traversed
                String homeroom=r.getString("homeroom_class");// assigning value from home_class column to the string homeroom
                if(homeroom.equals(class_combo.getSelectedItem().toString())){// checking if homeroom class is already assinged to another teacher
                    flag=false;
                    JOptionPane.showMessageDialog(this,"Class teacher is aready assigned to "+class_combo.getSelectedItem().toString());
                }
            }
            
        }catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
            
            
            return flag;
}
    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
    if(this.validateEntries()&& checkClassValidation()) // calling other validation methods inside the class -- modularity
        updateRecords(); //calling method updateDatabase() to save entries of student the database table
        
    }//GEN-LAST:event_save_btnActionPerformed

    private void sendMail(){
                 MailMessage message = new MailMessage();
        // Set subject of the message, body and sender information
        message.setSubject("Login credentails for Elemantary School Management System");
        message.setHtmlBody("Your user ID is : "+this.id+ "  password : welcome@123");
        
        message.setFrom(new MailAddress("school_mgmt2023@outlook.com", "NMS Elemantary School Coordinator", false));//teacher mail id
       // Specify encoding 
       message.setBodyEncoding(Charset.forName("US-ASCII"));
        // Add To recipients and CC recipients
       message.getTo().addItem(new MailAddress(this.email,this.firstname+" "+this.lastname, false));
        // Create an instance of SmtpClient Class
        SmtpClient client = new SmtpClient();
        // Specify your mailing host server, Username, Password, Port
        client.setHost("smtp-mail.outlook.com");
        client.setUsername("school_mgmt2023@outlook.com");
        client.setPassword("welcome2023");
        client.setPort(587);
        try
        {
	// Client.Send will send this message
            client.send(message); 
            JOptionPane.showMessageDialog(this,"Your e-mail has been successfully sent.");
//            CoordinatorDashboard td=new  CoordinatorDashboard();
//            td.setVisible(true);
//            this.dispose();
        }
        catch (Exception ex){
	ex.printStackTrace();
       
}
    }
    private void class_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_class_comboActionPerformed
    public boolean validateEntries(){
        boolean flag=true;
       // first checking for any fields left blank 
       if(this.tchrID_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Teacher ID field cannot be left blank");
            flag=false;
        }
       else  if(this.teacherFirstName_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Firstname field cannot be left blank");
            flag=false;
        }
       else  if(this.teacherLastName_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Lastname field cannot be left blank");
            flag=false;
        }
       else  if(this.class_combo.getSelectedItem().toString().equals("Select"))
        {
            JOptionPane.showMessageDialog(this,"Please choose a Home Room Class");
            flag=false;
        }
       else if(this.teacherSubject_combo.getSelectedItem().toString().equals("Select"))
        {
            JOptionPane.showMessageDialog(this,"Please choose a Subject ");
            flag=false;
        }
       else  if(this.teacherPhoneNumber_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Contact number field cannot be left blank");
            flag=false;
        }
        else if(this.teacherEmailID_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Email ID field cannot be left blank");
            flag=false;
        }
       
        
       
        //phone number format checking and prescence checking code 
        if(!teacherPhoneNumber_txt.getText().isEmpty()){
            //https://stackoverflow.com/questions/42104546/java-regular-expressions-to-validate-phone-numbers
            Pattern p = Pattern.compile(("\\d{10}"));//only 10 digits allowed
            if(!p.matcher(teacherPhoneNumber_txt.getText()).matches()){
                flag=false;
                JOptionPane.showMessageDialog(this, "Invalid Contact number");
            }
        }
        //email format checking and prescence cheking code 
        if(!this.teacherEmailID_txt.getText().isEmpty()){
             //reference:https://howtodoinjava.com/java/regex/java-regex-validate-email-address/
            /*
            [A-Z] characters allowed
                [a-z] characters allowed
                [0-9] numbers allowed
            Additionally email may contain only dot(.), dash(-) and underscore(_)
            Rest all characters are not allowed
            */
             String regex = "^[A-Za-z0-9+_.-]+@(.+)$";
             Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(this.teacherEmailID_txt.getText());// calling matcher function to check format of email
            if(matcher.matches()==false){
                flag=false;
                JOptionPane.showMessageDialog(this, "Invalid Email");
            }
        }
               
        if(flag){// reference variables are set values if flag is true
            this.id=Integer.parseInt(this.tchrID_txt.getText());
            this.firstname=this.teacherFirstName_txt.getText();
            this.lastname=this.teacherLastName_txt.getText();
            this.homeroomClass=this.class_combo.getSelectedItem().toString();
            this.subject=this.teacherSubject_combo.getSelectedItem().toString();
            this.contactno=this.teacherPhoneNumber_txt.getText();
            this.email=this.teacherEmailID_txt.getText();
           
        }
 
    return  flag;
    
}
    
            
        
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JCheckBox c1a;
    private javax.swing.JCheckBox c1b;
    private javax.swing.JCheckBox c1c;
    private javax.swing.JCheckBox c1d;
    private javax.swing.JCheckBox c2a;
    private javax.swing.JCheckBox c2b;
    private javax.swing.JCheckBox c2c;
    private javax.swing.JCheckBox c2d;
    private javax.swing.JCheckBox c3a;
    private javax.swing.JCheckBox c3b;
    private javax.swing.JCheckBox c3c;
    private javax.swing.JCheckBox c3d;
    private javax.swing.JCheckBox c4a;
    private javax.swing.JCheckBox c4b;
    private javax.swing.JCheckBox c4c;
    private javax.swing.JCheckBox c4d;
    private javax.swing.JCheckBox c5a;
    private javax.swing.JCheckBox c5b;
    private javax.swing.JCheckBox c5c;
    private javax.swing.JCheckBox c5d;
    private javax.swing.JComboBox class_combo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField tchrID_txt;
    private javax.swing.JTextField teacherEmailID_txt;
    private javax.swing.JTextField teacherFirstName_txt;
    private javax.swing.JTextField teacherLastName_txt;
    private javax.swing.JTextField teacherPhoneNumber_txt;
    private javax.swing.JComboBox teacherSubject_combo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateRecords() {
         
    try{
        //loading and registering drivers
         Class.forName("java.sql.DriverManager");
         /*
         calling getCOnnection method of My_DB_Con class to establish
         a connection with election_db database
         */
         Connection con=Db_Connection.connectDbMethod();// establishing connection with database
         Statement s=con.createStatement();
            //inserting values from jFrame form to teacher_details table in sql database
            int x = s.executeUpdate("insert into teacher_details values("+this.id+",'"+this.firstname+"',"
                    + " '"+this.lastname+"',"
                    + "'"+this.homeroomClass+"','"+this.subject+"' ,'"+this.listClass.get(0)+"' ,'"+this.listClass.get(1)+"','"+this.listClass.get(2)+"' ,'"+this.listClass.get(3)+"','"+this.listClass.get(4)+"','"+this.contactno+"','"+this.email+"')");
            
            //inserting values into logindetails table in sql database
            int y = s.executeUpdate("insert into logindetails values("+this.id+",'"+this.firstname+"',"
                    + " '"+this.lastname+"',"
                    + "'"+this.category+"','"+this.password+"' )");
            
            if(x>0 && y>0){// will only execute if there are 2 postive integer outputs showing that data is added in database
                    JOptionPane.showMessageDialog(this,"teacher details added in the database successfully");//message to show success
                    AddTeacher lp=new AddTeacher();
                    sendMail();// emailing the credentials
                    lp.setVisible(true);// redirecting to the AddTeacher form after showing message
                    this.dispose();
            }
            else
            {
               JOptionPane.showMessageDialog(this,"Technical Error!"); 
            }
            
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,e.getMessage());
    
    }
    }
        
        
        
         }

   

