/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elementaryschoolmanagementsystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author ASUS
 */
public class ClassTeacherDashboard extends javax.swing.JFrame {

    /**
     * Creates new form ClassTeacherDashboard
     */
    public ClassTeacherDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Message_lbl.setText(LoginPage.getMessage());//USES relationship-association
    }
    
    public void openSubjectDetails()// automatically opens the appropriate subject details from for the teacher based on teacher ID and Subject
    {
    String subject = getTeacherSubject();
      
    if(subject.equals("Science"))
      {
        SciencesSubjectRecord show = new SciencesSubjectRecord();
        show.setVisible(true);
        this.dispose(); 
      }
      
    else if(subject.equals("Mathematics"))
      {
        MathSubjectRecord show = new MathSubjectRecord();  
        show.setVisible(true);
        this.dispose();  
      }
    else if(subject.equals("Social Studies")) 
      {
        SocialStudiesSubjectRecord show = new SocialStudiesSubjectRecord();  
        show.setVisible(true);
        this.dispose();
      }
    else if(subject.equals("English")) 
      {
        EnglishSubjectRecord show = new EnglishSubjectRecord();  
        show.setVisible(true);
        this.dispose();
      }
    else if(subject.equals("ICT")) 
      {
        ComputersSubjectRecord show = new ComputersSubjectRecord();  
        show.setVisible(true);
        this.dispose();
      }
    else if(subject.equals("Hindi")) 
      {
        HindiSubjectRecord show = new HindiSubjectRecord();  
        show.setVisible(true);
        this.dispose();
      }
    else if(subject.equals("General Knowledge")) 
      {
        GkSubjectRecord show = new GkSubjectRecord();  
        show.setVisible(true);
        this.dispose();
      }
    } 
    
    public String getTeacherSubject()// to fetch the subject the teacher teaches
    {
       String teacher_subject =null;
       try{
                Class.forName("java.sql.DriverManager");
                Connection con = Db_Connection.connectDbMethod(); 
                Statement st=con.createStatement(); 
                ResultSet rs=st.executeQuery("select subject from teacher_details where id="+LoginPage.id);
                if(rs.next()){
                    teacher_subject=rs.getString(1);
                    System.out.println(teacher_subject);
                    
                    
                }
        }catch(Exception e){
          e.printStackTrace();
    }
       return teacher_subject;
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        homeroomDetails_btn = new javax.swing.JButton();
        subjectDetails_btn = new javax.swing.JButton();
        changePassword_btn = new javax.swing.JButton();
        Message_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Class Teacher Dashboard", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        homeroomDetails_btn.setBackground(new java.awt.Color(153, 204, 255));
        homeroomDetails_btn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        homeroomDetails_btn.setText("Homeroom Details");
        homeroomDetails_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeroomDetails_btnActionPerformed(evt);
            }
        });

        subjectDetails_btn.setBackground(new java.awt.Color(153, 204, 255));
        subjectDetails_btn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        subjectDetails_btn.setText("Subject Details");
        subjectDetails_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectDetails_btnActionPerformed(evt);
            }
        });

        changePassword_btn.setBackground(new java.awt.Color(153, 204, 255));
        changePassword_btn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        changePassword_btn.setText("Change Password");
        changePassword_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassword_btnActionPerformed(evt);
            }
        });

        Message_lbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Message_lbl.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePassword_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectDetails_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeroomDetails_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(209, 209, 209))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Message_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Message_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(homeroomDetails_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(subjectDetails_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(changePassword_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Elementary School Manager");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeroomDetails_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeroomDetails_btnActionPerformed
        // TODO add your handling code here:
        HomeroomDetails show = new HomeroomDetails();
        show.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeroomDetails_btnActionPerformed

    private void subjectDetails_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectDetails_btnActionPerformed
        // TODO add your handling code here:
       // THIS BUTTON HAS TO AUTOMCATICALLY SEND THE TEACHER TO THEIR PAGE WITHOUGHT HAVING TO SELECT THEIR SUBJECT
       openSubjectDetails();
    }//GEN-LAST:event_subjectDetails_btnActionPerformed

    private void changePassword_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassword_btnActionPerformed
        // TODO add your handling code here:
        ChangePassword show = new ChangePassword();
        show.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_changePassword_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassTeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassTeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassTeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassTeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassTeacherDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message_lbl;
    private javax.swing.JButton changePassword_btn;
    private javax.swing.JButton homeroomDetails_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton subjectDetails_btn;
    // End of variables declaration//GEN-END:variables
}
